variable "aws_region" { type = string default = "ap-south-1" }
variable "project_name" { type = string default = "octabyte-devops" }
variable "vpc_cidr" { type = string default = "10.20.0.0/16" }
variable "availability_zones" { type = list(string) default = ["ap-south-1a","ap-south-1b"] }
variable "instance_type" { type = string default = "t3.micro" }
variable "db_instance_class" { type = string default = "db.t3.micro" }
variable "db_name" { type = string default = "appdb" }
variable "db_username" { type = string default = "appuser" }
variable "app_port" { type = number default = 3000 }
variable "ami_id" { type = string default = "" }
